name = str(input("enter the name"))
department=str(input("enter the Department"))
cgpa = float(input("enter the cgpa"))
mobilenumber = int(input("enter the mobilenumber"))
bloodgroup = (input("enter the bloodgroup"))
print(name)
print(department)
print(cgpa)
print(mobilenumber)
print(bloodgroup)
